# Generated by Django 3.0.8 on 2020-09-10 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
