# Generated by Django 3.0.5 on 2020-10-03 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201003_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='negativesamples',
            options={'managed': True},
        ),
    ]
