# Generated by Django 3.0.5 on 2020-10-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20201003_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negativesamples',
            name='accidet',
        ),
        migrations.RemoveField(
            model_name='negativesamples',
            name='id',
        ),
        migrations.RemoveField(
            model_name='negativesamples',
            name='visiblite',
        ),
        migrations.AddField(
            model_name='negativesamples',
            name='accident',
            field=models.IntegerField(blank=True, db_column='Accident', null=True),
        ),
        migrations.AddField(
            model_name='negativesamples',
            name='id_acc',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='negativesamples',
            name='visibilite',
            field=models.IntegerField(blank=True, db_column='Visibilite', null=True),
        ),
        migrations.AlterField(
            model_name='negativesamples',
            name='cat_veh',
            field=models.CharField(blank=True, db_column='CAT_VEH', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='negativesamples',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='negativesamples',
            name='date_naiss_chauff',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='negativesamples',
            name='wilaya',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
