# Generated by Django 3.0.5 on 2020-10-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20201003_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='negativesamples',
            name='cause_acc',
            field=models.CharField(blank=True, db_column='CAUSE_ACC', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='negativesamples',
            name='visibilite',
            field=models.IntegerField(blank=True, db_column='visibilite', null=True),
        ),
    ]
